<?php

namespace AppBundle\Repository;

/**
 * HelpRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
